# Site settings
baseurl = "/"
languageCode = "en-us"
theme = ["docdock", "bizcraft"]
#theme = ["docdock", "bizcraft"]
#theme = ["bizcraft", "hugo-theme-learn"]
#theme = ["hugo-theme-learn"]
enableGitInfo = false
version = "0.15.0"
publishDir = "docs"
title = "Velociraptor / Dig deeper"

[outputs]
  home = ["HTML", "JSON"]

[frontmatter]
  date = ["date", "lastmod"]
  lastmod = ["lastmod", ":git", "date"]

  # Google Analytics tracking
  googleAnalytics = ""

[params]
  #  Settings from https://learn.netlify.com/en/basics/configuration/
  name = "Velociraptor"
  title = "Velociraptor / Dig deeper"
  description = "Velociraptor / Dig deeper"
  images = ["/images/velo_small.png"]
  themeVariant = "mine"
  themeStyle = "original"
  disableSearch = false
  disableBreadcrumb = true
  disableHomeIcon = true

  # Generates too much churn in git tree.
  disableAssetsBusting = true

  [params.style]
    #background = "secondary"

  # Theme customizations
  # Assets relative to 'static/'
  [params.custom]
    favicon = "/images/favicon.ico"
    favicon_ico_sizes = "16x16 32x32"
    favicon_png = "/images/favicon.png"
    favicon_svg = "/images/logo.svg"

  # Piwik tracking
  [params.analytics.piwik]
    #url = ""
    #id = ""
    #domain = "" # Track subdomains via "*.example.com"
    # Optional hash for integrity check
    #hash = "sha512-RfeD0pacGTqy9m7U6PgehQfS4cc7SIt+e+P+H5e848kEvB/RW84CUGO3O4O3LNbxjevym6KPUZ8muPsMrI8WIw=="

  # Optional, global disable switch for fontawesome related files
  # For custom fontawesome js files use the custom.js method
  [params.fontawesome]
    disabled = false
    pro = false

  [params.colors]
    primary = "#00838F"
    secondary = "#868e96"
    success = "#00aa00"
    info = "#00c9dc"
    warning = "#fdf314"
    danger = "#dc1200"
    light = "#f8f9fa"
    dark = "#343a40"

  [[params.navbar]]
  title = "Home"
  link = "/"

  [[params.navbar]]
  title = "Documentation"
  link = "/docs"

  [[params.navbar]]
  title = "Download"
  link = ""
  url = "https://github.com/Velocidex/velociraptor"

  [[params.navbar]]
  title = "Support"
  link = ""
  url = "https://groups.google.com/forum/#!forum/velociraptor-discuss"

  [[params.navbar]]
  title = "<i class=\"fab fa-github\"></i>"
  link = ""
  url = "https://github.com/Velocidex/velociraptor"
