content/docs/artifacts/linux.md:
  title: Linux Artifacts
  linktitle: Linux Artifacts
  description: Linux Artifacts
  prefix: Linux.
  weight: 10

content/docs/artifacts/windows_system.md:
  title: Windows System
  linktitle: Windows System
  description: These artifacts collect information related to the windows system itself.
  prefix: Windows.Sys
  weight: 20

content/docs/artifacts/server.md:
  title: Server Artifacts
  linktitle: Server Artifacts
  description: These artifacts are intended to run on the server.
  prefix: Server.
  weight: 30

content/docs/artifacts/triage.md:
  title: Windows Triage Artifacts
  linktitle: Windows Triage
  description: Triage artifacts simply collect various files as quickly as possible. In recent versions of Velociraptor, many of the triage artifacts have been merged into the Windows.KapeFiles.Targets artifact.
  prefix:
    - Windows.Triage.
    - Windows.KapeFiles.
    - Triage.
    - Windows.Forensics
  weight: 40

content/docs/artifacts/detection.md:
  title: Windows Malware Detection
  linktitle: Windows Detection
  description: These artifacts attempt to detect the presence of specific compromizes.
  prefix:
    - Windows.Detection
    - Windows.Persist
  weight: 50

content/docs/artifacts/events.md:
  title: Windows Event Monitoring
  linktitle: Windows Monitoring
  description: These event artifacts stream monitoring events from the endpoint. We collect these events on the server.
  toc: true
  prefix:
    - Windows.Events.
  weight: 60

content/docs/artifacts/misc.md:
  title: Miscelaneous Artifacts
  linktitle: Miscelaneous
  description: Various Artifacts which do not fit into other categories.
  toc: true
  prefix:
    - ""
  weight: 70
